baseURL: https://ryanstreur.com
languageCode: en-us
defaultContentLanguage: en

title: Ryan Streur
author: Ryan Streur

theme: hugo-theme-clarity

enableGitInfo: true

pygmentsCodefences: true
pygmentsUseClasses: true

copyright: Copyright Ryan Streur, 2019 # This message is only used by the RSS template.

enableEmoji: true # Shorthand emojis in content files - https://gohugo.io/functions/emojify/

blackfriday:
  hrefTargetBlank: true

taxonomies:
  tag: tags
